project_name: "single_cell_immune_atlas"
seed: 1337
organism: "human"

datasets:
  - id: "MELANOMA_CENSUS"
    modality: "scRNA"
    url: "data/raw/melanoma_census.h5ad"
    platform: "mixed"
    cancer_type: "melanoma"
  - id: "NSCLC_CENSUS"
    modality: "scRNA"
    url: "data/raw/nsclc_census.h5ad"
    platform: "mixed"
    cancer_type: "NSCLC"
  - id: "BREAST_CENSUS"
    modality: "scRNA"
    url: "data/raw/breast_census.h5ad"
    platform: "mixed"
    cancer_type: "Breast"
  - id: "RCC_NIVOLUMAB_CENSUS"
    modality: "scRNA"
    url: "data/raw/rcc_nivo_census.h5ad"
    platform: "mixed"
    cancer_type: "RCC"
  - id: "NSCLC_PEMBROLIZUMAB_CENSUS"
    modality: "scRNA"
    url: "data/raw/nsclc_pembro_census.h5ad"
    platform: "mixed"
    cancer_type: "NSCLC"
  - id: "NSCLC_NIVO_IPI_CENSUS"
    modality: "scRNA"
    url: "data/raw/nsclc_nivo_ipi_census.h5ad"
    platform: "mixed"
    cancer_type: "NSCLC"
  - id: "UROTHELIAL_ATEZOLIZUMAB_CENSUS"
    modality: "scRNA"
    url: "data/raw/urothelial_atezo_census.h5ad"
    platform: "mixed"
    cancer_type: "Urothelial"
  - id: "RCC_COMBINATION_CENSUS"
    modality: "scRNA"
    url: "data/raw/rcc_combo_census.h5ad"
    platform: "mixed"
    cancer_type: "RCC"
  - id: "PDAC_ICI_CENSUS"
    modality: "scRNA"
    url: "data/raw/pdac_ici_census.h5ad"
    platform: "mixed"
    cancer_type: "PDAC"

qc:
  min_genes: 200
  max_genes: 6000
  max_mt_pct: 15

doublets:
  method: "scrublet"
  expected_doublet_rate: 0.06

integration:
  method: "scvi"   # options: "scvi" | "harmony"
  latent_dim: 30
  batch_key: "dataset_id"

neighbors:
  n_neighbors: 15
  n_pcs: 50

umap:
  min_dist: 0.4
  spread: 1.0

annotation:
  strategy: "markers"
  min_pct: 0.1

outputs:
  cellxgene_dir: "processed/cellxgene_release"
  figures_dir: "processed/figures"
