name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: env.yml
          environment-name: immune-atlas
          create-args: >-
            python=3.10

      - name: Install test dependencies
        run: micromamba run -n immune-atlas pip install -r tests/requirements.txt

      - name: Run pytest
        run: micromamba run -n immune-atlas pytest -q
